In [1]:
import torch
import numpy as np

# Independent Variables

In [2]:
x=[i for i in range(11)] #a list is created
x

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [3]:
x=np.array(x) #we have to convert them to array and then to tensor
#datatype should be float for gradient calculations
x.shape
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
x=x.reshape(-1,1) #change from single array to 11 nested arrays 
x

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [5]:
x.shape

(11, 1)

# Dependent Variables

In [6]:
y=[2*i+1 for i in x]
y=np.array(y,dtype=np.float32)

In [7]:
y=y.reshape(-1,1)
y

array([[ 1.],
       [ 3.],
       [ 5.],
       [ 7.],
       [ 9.],
       [11.],
       [13.],
       [15.],
       [17.],
       [19.],
       [21.]], dtype=float32)

In [8]:
y.shape

(11, 1)

In [9]:
import torch.nn as nn #Helps in building our linear regression model
from torch.autograd import Variable

In [10]:
class LinearRegressionModel(nn.Module):
    def __init__(self,input_size,output_size):
        super(LinearRegressionModel,self).__init__()
        self.Linear=nn.Linear(input_dim,output_dim)
        
    def forward(self,x):
        out=self.Linear(x)
        return out

In [11]:
input_dim=1;output_dim=1
model=LinearRegressionModel(input_dim,output_dim)

In [12]:
criterion=nn.MSELoss()

In [13]:
lr=.01
optimizer=torch.optim.SGD(model.parameters(),lr=lr)

In [14]:
epochs=100
for ep in range(epochs):
    ep+=1
    inputs=Variable(torch.from_numpy(x))
    labels=Variable(torch.from_numpy(y))
    
#     Clear gradients wrt every parameter in each epoch
    optimizer.zero_grad()
    
#     y=a*x+b . The forward function is being called here
    outputs=model(inputs)
    
#     Calculate loss
    loss=criterion(outputs,labels)
    
#     Calculate backpropagation
    loss.backward()
    
#     Update parameters
    optimizer.step()
    
    print('epoch {},loss {}'.format(ep,loss.data[0]))

RuntimeError: Expected object of type torch.FloatTensor but found type torch.IntTensor for argument #4 'mat1'

In [ ]:
predicted=model(Variable(torch.from_numpy(x))).data.numpy()

In [ ]:
predicted

In [ ]:
y

In [ ]:
save_model=True
if save_model is True:
    torch.save(model.state_dict(),'practice.pkl')

In [ ]:
load_model=True
if load_model is True:
    model.load_state_dict(torch.load('practice.pkl'))