In [1]:
import numpy as np

In [25]:
import pandas as pd

In [6]:
import torch

In [9]:
arr=[[1,2],[3,4]] #nested list

In [10]:
np.array(arr) #numpy for array definition

array([[1, 2],
       [3, 4]])

In [11]:
torch.tensor(arr) #tprch for tensor definition

tensor([[1, 2],
        [3, 4]])

In [20]:
np.ones((3,2),dtype=int) #rows & columns & default dtype is float .It returns an array 

array([[1, 1],
       [1, 1],
       [1, 1]])

In [19]:
np.ones((3)) # when only one para given,it takes column as 3

array([1., 1., 1.])

In [21]:
torch.ones((2,2))

tensor([[1., 1.],
        [1., 1.]])

In [28]:
np.random.rand(2,2)

array([[0.21646554, 0.57967025],
       [0.6811113 , 0.75068772]])

In [23]:
torch.rand(2,2) #torch for random intialization

tensor([[0.4787, 0.0808],
        [0.8422, 0.6982]])

# Seeds for Reproducibilty

In [33]:
#Seed - to reproduce same random numbers over and over again for our models
np.random.seed(0)
np.random.rand(2,2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [34]:
np.random.seed(0)
np.random.rand(2,2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [35]:
#No seed
np.random.rand(2,2) #will get different numbers from first two

array([[0.4236548 , 0.64589411],
       [0.43758721, 0.891773  ]])

In [37]:
#torch seed
torch.manual_seed(1)
torch.rand(2,2)

tensor([[0.7576, 0.2793],
        [0.4031, 0.7347]])

In [38]:
torch.manual_seed(1)
torch.rand(2,2)

tensor([[0.7576, 0.2793],
        [0.4031, 0.7347]])

In [39]:
#torch no seed
torch.rand(2,2)

tensor([[0.0293, 0.7999],
        [0.3971, 0.7544]])

In [40]:
#Seed for GPU is different
if torch.cuda.is_available():
    torch.cuda.manual.seed_all(0)

# Numpy and Torch Bridge

In [47]:
np_array=np.ones((2,2))
print(type(np_array))

<class 'numpy.ndarray'>


In [43]:
#Convert np array to torch tensor 
torch_tensor=torch.from_numpy(np_array)

In [45]:
print (torch_tensor)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)


In [46]:
print(type(torch_tensor))

<class 'torch.Tensor'>


In [57]:
 #np_array_new=np.ones((2,2),dtype=np.int8) #certain dtypes of arrays can only be converted to tensor #check int8
 #torch.from_numpy(np_array_new)

TypeError: can't convert np.ndarray of type numpy.int8. The only supported types are: double, float, float16, int64, int32, and uint8.

In [59]:
np_array_new=np.ones((2,2),dtype=np.double) #certain dtypes of arrays can only be converted to tensor
torch.from_numpy(np_array_new)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

# Torch to Numpy

In [60]:
torch_tensor=torch.ones(2,2)

In [61]:
type(torch_tensor)

torch.Tensor

In [62]:
torch_to_numpy=torch_tensor.numpy()

In [63]:
type(torch_to_numpy)

numpy.ndarray

# Tensors on CPU vs GPU

In [68]:
#CPU
tensor_cpu=torch.ones(2,2)

In [69]:
#CPU to GPU
if torch.cuda.is_available():
    tensor_cpu.cuda()

In [70]:
#GPU to CPU
tensor_cpu.cpu()

tensor([[1., 1.],
        [1., 1.]])