In [85]:
import numpy as np

In [86]:
import pandas as pd

In [87]:
import torch

In [4]:
arr=[[1,2],[3,4]] #nested list

In [5]:
np.array(arr) #numpy for array definition

array([[1, 2],
       [3, 4]])

In [6]:
torch.tensor(arr) #torch for tensor definition

tensor([[1, 2],
        [3, 4]])

In [7]:
np.ones((3,2),dtype=int) #rows & columns & default dtype is float .It returns an array 

array([[1, 1],
       [1, 1],
       [1, 1]])

In [8]:
np.ones((3)) # when only one para given,it takes column as 3

array([1., 1., 1.])

In [9]:
torch.ones((2,2))

tensor([[1., 1.],
        [1., 1.]])

In [10]:
np.random.rand(2,2)

array([[0.59958077, 0.63540333],
       [0.72492937, 0.34980971]])

In [11]:
torch.rand(2,2) #torch for random intialization

tensor([[0.0795, 0.2347],
        [0.4188, 0.6730]])

# Seeds for Reproducibilty

In [12]:
#Seed - to reproduce same random numbers over and over again for our models
np.random.seed(0)
np.random.rand(2,2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [13]:
np.random.seed(0)
np.random.rand(2,2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [14]:
#No seed
np.random.rand(2,2) #will get different numbers from first two

array([[0.4236548 , 0.64589411],
       [0.43758721, 0.891773  ]])

In [15]:
#torch seed
torch.manual_seed(1)
torch.rand(2,2)

tensor([[0.7576, 0.2793],
        [0.4031, 0.7347]])

In [16]:
torch.manual_seed(1)
torch.rand(2,2)

tensor([[0.7576, 0.2793],
        [0.4031, 0.7347]])

In [17]:
#torch no seed
torch.rand(2,2)

tensor([[0.0293, 0.7999],
        [0.3971, 0.7544]])

In [18]:
#Seed for GPU is different
if torch.cuda.is_available():
    torch.cuda.manual.seed_all(0)

# Numpy and Torch Bridge

In [19]:
np_array=np.ones((2,2))
print(type(np_array))

<class 'numpy.ndarray'>


In [20]:
#Convert np array to torch tensor 
torch_tensor=torch.from_numpy(np_array)

In [21]:
print (torch_tensor)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)


In [22]:
print(type(torch_tensor))

<class 'torch.Tensor'>


In [23]:
 np_array_new=np.ones((2,2),dtype=np.int8) #certain dtypes of arrays can only be converted to tensor #check int8
 torch.from_numpy(np_array_new)

TypeError: can't convert np.ndarray of type numpy.int8. The only supported types are: double, float, float16, int64, int32, and uint8.

In [24]:
np_array_new=np.ones((2,2),dtype=np.double) #certain dtypes of arrays can only be converted to tensor
torch.from_numpy(np_array_new)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

# Torch to Numpy

In [69]:
torch_tensor=torch.ones(2,2)

In [26]:
type(torch_tensor)

torch.Tensor

In [27]:
torch_to_numpy=torch_tensor.numpy()

In [28]:
type(torch_to_numpy)

numpy.ndarray

# Tensors on CPU vs GPU

In [29]:
#CPU
tensor_cpu=torch.ones(2,2)

In [30]:
#CPU to GPU
if torch.cuda.is_available():
    tensor_cpu.cuda()

In [31]:
#GPU to CPU
tensor_cpu.cpu()

tensor([[1., 1.],
        [1., 1.]])

# Tensor Operations

# Resizing Tensors

In [72]:
a=torch.ones(3,2)
print(a)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [49]:
print(a.size)

<built-in method size of Tensor object at 0x0000000003C3CC18>


In [50]:
a.view(4)

tensor([1., 1., 1., 1.])

In [73]:
a.size()

torch.Size([3, 2])

# Element wise Addition

In [61]:
a=torch.ones(2,2)

In [62]:
b=torch.ones(2,2)

In [63]:
c=a+b  #c=a-b
print(c)

tensor([[2., 2.],
        [2., 2.]])


In [64]:
c=torch.add(a,b) #Another way of doing addition
print(c)


#torch.sub(a,b) doesn't work. a.sub(b)---> b subtracted from a


tensor([[2., 2.],
        [2., 2.]])


In [65]:
#In place addition i.e it changes the original value
print("old c tensor")
print('-'*60)
print (c)

c.add_(a) #a.sub_(b)
print("new c tensor")
print('-'*60)
print (c)

old c tensor
------------------------------------------------------------
tensor([[2., 2.],
        [2., 2.]])
new c tensor
------------------------------------------------------------
tensor([[3., 3.],
        [3., 3.]])


# Element wise Multiplication

In [57]:
a=torch.ones(2,2)
b=torch.zeros(2,2)
a*b #b/a

tensor([[0., 0.],
        [0., 0.]])

In [58]:
print(torch.mul(a,b)) #torch.div(b,a)
print(a) #a values dont change

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])


In [59]:
#inplace
print(a.mul_(b)) #b.div_(a)
print(a) # a values get updated

tensor([[0., 0.],
        [0., 0.]])
tensor([[0., 0.],
        [0., 0.]])


# Tensor Mean

In [66]:
a=torch.tensor([1,2,3,4,5,6,7,8,9,10],dtype=torch.float64)

In [67]:
a.size()

torch.Size([10])

In [68]:
a.mean(dim=0)

tensor(5.5000, dtype=torch.float64)

In [70]:
a=torch.tensor([[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10]],dtype=torch.float64)

In [71]:
a.size()

torch.Size([2, 10])

In [75]:
a.mean(dim=1) #dim value changes

tensor([5.5000, 5.5000], dtype=torch.float64)

# Tensor Standard deviation

In [76]:
a=torch.tensor([1,2,3,4,5,6,7,8,9,10],dtype=torch.float64)

In [77]:
a.std(dim=0)

tensor(3.0277, dtype=torch.float64)

In [77]:
x = torch.tensor([[1., -1.], [1., 1.]], requires_grad=True)
out = x.pow(2)
print (out)

tensor([[1., 1.],
        [1., 1.]], grad_fn=<PowBackward0>)


In [81]:
x = torch.tensor([[1., -1.], [1., 1.]], requires_grad=True)
out = x.pow(2).sum()
print (out)

tensor(4., grad_fn=<SumBackward0>)


In [82]:
out.backward()
x.grad

tensor([[ 2., -2.],
        [ 2.,  2.]])

In [104]:
tensor = torch.ones(())
tensor.new_empty((2, 3))

tensor([[-108531296.0000,          0.0000,          0.0000],
        [         0.0000,          0.0000,          0.0000]])