# Variables & Gradients

A variable wraps a tensor

Allows Accumulation of gradients

In [21]:
import torch

In [3]:
from torch.autograd import Variable

In [4]:
a=Variable(torch.ones(2,2),requires_grad=True) #Variables allow you to accumulate graadients and behve similar to tensors  
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [5]:
torch.ones(2,2) #this not a variable

tensor([[1., 1.],
        [1., 1.]])

In [6]:
b=Variable(torch.ones(2,2),requires_grad=True)

In [7]:
print(a+b)
print(torch.add(a,b)) #all mathematical operations syntax is similar to tensor

tensor([[2., 2.],
        [2., 2.]], grad_fn=<ThAddBackward>)
tensor([[2., 2.],
        [2., 2.]], grad_fn=<ThAddBackward>)


# Gradients

In [24]:
torch.tensor([[1],[2]])

tensor([[1],
        [2]])

In [25]:
x=Variable(torch.ones(2),requires_grad=True) #2 rows=2 samples
x

tensor([1., 1.], requires_grad=True)

In [26]:
y=5*(x+1)**2 #predict y with those 2 samples respectively(incase of cost function it will be sub from actual y)
print (y)

tensor([20., 20.], grad_fn=<MulBackward>)


In [27]:
#for i in torch.len(y):
    #print(i)

In [28]:
o=(1/2)*torch.sum(y) #taking average of all samples inorder to get loss error of one iteration
o

tensor(20., grad_fn=<MulBackward>)

In [29]:
o.backward() #backward should have one a scalar value only(i.e 1 element tensor) to get do/dx 

In [30]:
print(x.grad) #gives x(weights) for each feature

tensor([10., 10.])
