# Variables & Gradients

A variable wraps a tensor

Allows Accumulation of gradients

In [1]:
import torch

In [2]:
from torch.autograd import Variable

In [4]:
a=Variable(torch.ones(2,2),requires_grad=True)
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [5]:
torch.ones(2,2) #this not a variable

tensor([[1., 1.],
        [1., 1.]])

In [7]:
b=Variable(torch.ones(2,2),requires_grad=True)

In [10]:
print(a+b)
print(torch.add(a,b)) #all mathematical operations syntax is similar to tensor

tensor([[2., 2.],
        [2., 2.]], grad_fn=<ThAddBackward>)
tensor([[2., 2.],
        [2., 2.]], grad_fn=<ThAddBackward>)
